### ISSUE TITLE
Attempted import error: 'event' is not exported from 'd3-selection'.

### ISSUE THREAD

**Issue by kyleawayan** [unkleho/d3-render#11]
I'm trying to use this with Next.js, and when I import it using `import render from "d3-render"` I get this error:
```
./node_modules/d3-render/dist/d3-render.esm.js
Attempted import error: 'event' is not exported from 'd3-selection'.
```
I looked at `d3-selection` in my `node-modules` and it looks like `event` is no longer exported from it. 

For now, I just remove `event` from `import { select, namespace, event, selection } from 'd3-selection'` in `d3-render/dist/d3-render.esm.js`, and it works (but obviously without whatever `events` did).

I don't really need events right now for my use case. I also want to say thank you for this module and your great tutorial on [your bubble chart](https://observablehq.com/@unkleho/covid-19-bubble-chart-with-d3-render)!

**Comment by LucasLongarini** [comment]
I am having this exact same issue in Next.js. My solution was to downgrade `d3-selection` to `v1.4.2`. This is not an ideal solution but the best I can do for now without altering the contents of node-modules.

**Comment by Cgg** [comment]
Just hit that this morning as well. That would be because `d3-selection` v2 removed `d3.event` and got released in August last year, whereas this repo's `package.json` still only specify a dependency >= 1.4.0. Either the peer dependency needs bumping to >= 2.0.0 and the code updating accordingly (looks straightforward according to https://observablehq.com/embed/@d3/d3-selection-2-0?cells=events ) or the package.json should be updated to limit the peer dependency's range to < 2.0.0.

**Comment by Cgg** [comment]
I've opened #13 which would fix this issue by updating the D3 dependency to ^6.

If the desire is to stick with v5 I am happy to submit another PR instead to restrict the peer deps versions.

@unkleho thoughts?

**Comment by unkleho** [comment]
I've just published v0.3.0, should be compatible with D3 v6 and selection v2. Thanks again for your help @Cgg.

**Comment by Cgg** [comment]
My pleasure! Thank you for making this, and reviewing my PR :-)

**Comment by Cgg** [comment]
Just updated my dependency and all is well, this can be closed.
